---
vagrant_user: dguser
# Set to the hostname of the server.
drupal_domain: "rootstalk.grinnell.edu"

# Add only the `apache_vhosts` or `nginx_hosts` you need. If installing a
# single Drupal site, the variable should look like this (Apache):
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

# Only install extras that you will need/use on your site, and don't install
# development-related software on production environments!
installed_extras:
  - drush
  # - memcached
  # - redis
  # - solr
  # - varnish

# Disable the dashboard page. Also remove any unneeded virtualhosts.
dashboard_install_dir: ''

# Enable a more hardened security configuration.
extra_security_enabled: true

# Restrict the firewall to only ports that are required for external services.
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
firewall_log_dropped_packets: true

# Set Apache to listen on port 81 (internal only), and Varnish on 80.
apache_listen_port: "81"
varnish_listen_port: "80"
varnish_default_backend_port: "81"

# Adjust the following for the selected OS!
drupal_group: www-data

drupal_composer_dependencies:
  - "drupal/devel:*"
  - "drupal/bootstrap:*"
  - "drupal/pdf:*"
  - "drupal/pathauto:*"
  - "drupal/calendar:*"
  - "drupal/views_templates:*"
  - "drupal/google_analytics:*"
  - "drupal/google_analytics_reports:*"
  - "drupal/embed:*"
  - "drupal/entity_embed:*"
  - "drupal/taxonomy_menu:*"
  - "drupal/video_embed_field:*"
  - "drupal/blog:*"
  - "drupal/ldap:*"
  - "drupal/authorization:*"

drupal_enable_modules:
  - bootstrap
  - devel
  - pdf
  - pathauto
  - calendar
  - views_templates
  - google_analytics
  - google_analytics_reports
  - embed
  - entity_embed
  - taxonomy_menu
  - video_embed_field
  - blog
  - ldap
  - authorization

drupal_default_theme: bootstrap

drupal_db_archive: "/tmp/rootstalk.tar.gz"

drupal_composer_install_dir: "/var/www/html/drupal"
drupal_site_name: "Rootstalk"
drupal_account_name: dguser
drupal_db_user: drupal
drupal_db_name: drupal

build_composer_project: true

# Since this will be a publicly-accessible instance of Drupal VM, make sure you
# configure secure passwords, especially for Drupal and MySQL!
drupal_account_pass: Grinne!!@dgu$er
drupal_db_password: Grinne!!drup@!
mysql_root_password: Grinne!!r00t
