---
vagrant_box: geerlingguy/centos7
vagrant_synced_folder_default_type: rsync
vagrant_hostname: rootstalk.dev
vagrant_machine_name: rootstalk
# Setting vagrant_ip to 0.0.0.0 implies that the auto_network plugin is installed.
# See Quick Start item 3 in https://github.com/geerlingguy/drupal-vm/blob/master/README.md.
# vagrant_ip: 0.0.0.0
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    type: rsync
    create: true

extra_packages:
  - sqlite
  - nano
  - figlet

# Adjust the following for the selected OS!
drupal_group: apache

drupal_composer_dependencies:
  - "drupal/devel:8.*"
  - "drupal/bootstrap:8.*"

drupal_enable_modules:
  - bootstrap
  - devel

drupal_default_theme: bootstrap

drupal_db_archive: "/var/www/drupalvm/none.dump"

# Additions below this line made initially in the 'rootstalk' branch.

drupal_composer_install_dir: "/var/www/drupal"
drupal_site_name: "Rootstalk"