---
- name: Check if site is already installed.
  command: >
    {{ drush_path }} status bootstrap
    chdir={{ drupal_core_path }}
  register: drupal_site_installed
  failed_when: "drupal_site_installed.stdout is undefined"
  changed_when: false
  become: no

- name: Install Drupal with drush.
  command: >
    {{ drush_path }} site-install {{ drupal_install_profile | default('standard') }} -y
    --site-name="{{ drupal_site_name }}"
    --account-name={{ drupal_account_name }}
    --account-pass={{ drupal_account_pass }}
    --db-url=mysql://{{ drupal_mysql_user }}:{{ drupal_mysql_password }}@localhost/{{ mysql_databases[0].name }}
    {{ drupal_site_install_extra_args | default([]) | join(" ") }}
    chdir={{ drupal_core_path }}
  notify: restart webserver
  when: "'Successful' not in drupal_site_installed.stdout"
  become: no

- name: Install configured modules with drush.
  command: >
    {{ drush_path }} pm-enable -y {{ drupal_enable_modules | join(" ") }}
    chdir={{ drupal_core_path }}
  when: "'Successful' not in drupal_site_installed.stdout"
  become: no

# Additions below this line made initially in the 'rootstalk' branch.

- name: Set proper drupal path ownership.
  file:
    path: "{{ drupal_composer_install_dir }}"
    state: directory
    owner: "{{ vagrant_user }}"
    group: "{{ drupal_group }}"
    recurse: yes
  become: yes

# http://drupal.stackexchange.com/questions/200771/how-do-i-change-the-default-theme-with-drush-master
- name: Set selected theme as default.
  command: >
    {{ drush_path }} -y config-set system.theme default {{ drupal_default_theme }}
    chdir={{ drupal_core_path }}/sites/default
  become: no

# Check if {{ drupal_db_archive }} file exists.  See config.yml for the file path.
- name: Checking if {{ drupal_db_archive }} exists.
  stat: path={{ drupal_db_archive }}
  register: restore_db

# If {{ drupal_db_archive }} file exists, restore it using drush.
# From the drupal web root (/var/www/drupalvm/drupal/web) use a command
#   like "drush archive-dump --destination=/var/www/drupalvm/rootstalk.tar.gz --no-core --overwrite" to create the dump.
- name: Restore previous drupal DB archive.
  command: >
    {{ drush_path }} -y archive-restore {{ drupal_db_archive }} default --tar-options='vz'--destination={{ drupal_core_path }}
  when: restore_db.stat.exists == True
  become: yes

# Check for pdf.js
- stat: path={{ drupal_core_path }}/libraries/pdf.js
  register: pdfjs_dist

# Fetch the pdf.js pre-built distribution
- name: Fetch pdf.js distribution
  git:
    repo: "https://github.com/mozilla/pdfjs-dist.git"
    dest: "{{ drupal_core_path }}/libraries"
    update: yes
  when: pdfjs_dist.stat.exists == False
